# build.yaml - tiny18 unified for GitHub Actions

---
include:
  # Right / Central
  - board: xiao_ble
    shield: "tiny18_r rgbled_adapter"
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_SPLIT=y
      -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
      -DCONFIG_ZMK_BLE_ROLE_CENTRAL=y
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_BT=y
      -DCONFIG_ZMK_BLE=y
      -DCONFIG_BT_DEVICE_NAME=\"tiny18\"

  # Left / Peripheral
  - board: xiao_ble
    shield: "tiny18_l rgbled_adapter"
    cmake-args: >
      -DCONFIG_ZMK_SPLIT=y
      -DCONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y
      -DCONFIG_ZMK_BLE_ROLE_PERIPHERAL=y
      -DCONFIG_BT=y
      -DCONFIG_ZMK_BLE=y
      -DCONFIG_BT_DEVICE_NAME=\"tiny18\"

  # Settings reset firmware
  - board: xiao_ble
    shield: settings_reset
