# This file generates the GitHub Actions matrix.
# ZMK user-config build matrix for tiny18 (XIAO BLE)

---
include:
  # Right / Central
  - board: xiao_ble
    shield: "tiny18_r rgbled_adapter"
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_BT=y
      -DCONFIG_BT_PERIPHERAL=y
      -DCONFIG_ZMK_BLE=y
      -DCONFIG_BT_DEVICE_NAME=\"tiny18\"

  # Left / Peripheral
  - board: xiao_ble
    shield: "tiny18_l rgbled_adapter"
    cmake-args: >
      -DCONFIG_BT=y
      -DCONFIG_BT_PERIPHERAL=y
      -DCONFIG_ZMK_BLE=y
      -DCONFIG_BT_DEVICE_NAME=\"tiny18\"

  # Settings reset firmware
  - board: xiao_ble
    shield: settings_reset
