# build.yaml - tiny18 (XIAO BLE) R/L unified - 最新 ZMK 対応

---
include:
  # Right / Central
  - board: xiao_ble
    shield: "tiny18_r rgbled_adapter"
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_SPLIT=y
      -DCONFIG_BT=y
      -DCONFIG_BT_CENTRAL=y
      -DCONFIG_ZMK_BLE=y
      -DCONFIG_BT_DEVICE_NAME=\"tiny18\"
      -DCONFIG_ZMK_STUDIO=y

  # Left / Peripheral
  - board: xiao_ble
    shield: "tiny18_l rgbled_adapter"
    cmake-args: >
      -DCONFIG_ZMK_SPLIT=y
      -DCONFIG_BT=y
      -DCONFIG_BT_PERIPHERAL=y
      -DCONFIG_ZMK_BLE=y
      -DCONFIG_BT_DEVICE_NAME=\"tiny18\"

  # Settings reset firmware
  - board: xiao_ble
    shield: settings_reset
