# build.yaml - tiny18 (XIAO BLE) GitHub Actions matrix
# 全文固定版

---
include:
  # Right / Central
  - board: xiao_ble
    shield: "tiny18_r rgbled_adapter"
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_BT=y
      -DCONFIG_BT_CENTRAL=y
      -DCONFIG_ZMK_BLE=y
      -DCONFIG_BT_DEVICE_NAME="tiny18_r"

  # Left / Peripheral
  - board: xiao_ble
    shield: "tiny18_l rgbled_adapter"
    cmake-args: >
      -DCONFIG_BT=y
      -DCONFIG_BT_PERIPHERAL=y
      -DCONFIG_ZMK_BLE=y
      -DCONFIG_BT_DEVICE_NAME="tiny18_l"

  # Optional: settings reset firmware
  - board: xiao_ble
    shield: settings_reset
